# Generated by Django 5.0.6 on 2024-05-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='computers')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='computers')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='computers')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.category')),
            ],
        ),
    ]
