# Generated by Django 5.0.6 on 2024-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='custom_specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
