# Generated by Django 5.0.6 on 2024-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_custom_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
    ]
