# Generated by Django 5.0.6 on 2024-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
