# Generated by Django 5.0.6 on 2024-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Shipped', max_length=20),
        ),
    ]
